# This is a basic workflow to help you get started with Actions

name: Unit Test & Lint

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: npm install

      # Runs a set of commands using the runners shell
      - name: Test
        run: npm test .

      - name: Install Pods
        run: npm run pod-install

      - name: Install Detox CLI
        run: npm install -g detox-cli

      - name: Install Home brew
        run: curl -fsSL -o install.sh https://raw.githubusercontent.com/Homebrew/install/master/install.sh

      - name: InstallBrew/Wix
        run: brew tap wix/brew

      - name: Update Brew packages
        run: brew upgrade

      - name: Install Apple Utils
        run: brew install applesimutils

      - name: Build & Test iOS Release
        run: npm run e2e:ios-release
